name: Update api.txt

on:
  # 不再用 schedule，用 workflow_dispatch 让外部触发
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # 最新稳定版

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run IP collection script
        run: python collect_api.py

      - name: Commit and push api.txt if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main

          if ! git diff --quiet api.txt; then
              git add api.txt
              git commit -m "Update CT api.txt"
              git pull --rebase origin main || true
              git push origin main || git push origin HEAD:main --force-with-lease
          fi

      - name: Debug info
        if: ${{ always() }}
        run: |
          echo "UTC time: $(date -u)"
          echo "Beijing time: $(date -d '+8 hour')"
          echo "Branch: $(git branch --show-current)"
