name: Update api.txt

on:
  schedule:
    # GitHub 使用 UTC 时间，北京时间 +8 小时
    # 每小时整点的第 5 分钟（北京时间） = UTC - 8 小时
    - cron: '5 * * * *'  # ✅ 北京时间每小时第5分钟执行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python ips.py

      - name: Commit and push api.txt if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          if ! git diff --quiet api.txt; then
              git add api.txt
              git commit -m "Auto update api.txt"
              git pull --rebase origin main || true
              git push origin main || git push origin HEAD:main --force-with-lease
          fi
